// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Models;

public partial class TDetalle
{
    public int Id { get; set; }

    public string Observaciones { get; set; }

    internal int ServicioId { get; set; }

    internal int TurnoId { get; set; }

    internal virtual TServicio Servicio { get; set; }

    internal virtual TTurno Turno { get; set; }
}