// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Models;

public partial class TServicio
{
    public int Id { get; set; }
    public string Nombre { get; set; }
    public double Costo { get; set; }
    public bool EnPromocion { get; set; }
    internal virtual ICollection<TDetalle> TDetalles { get; set; } = new List<TDetalle>();
}