// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Data.Models;

public partial class TurnoDbContext : DbContext
{
    public TurnoDbContext(DbContextOptions<TurnoDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<TDetalle> TDetalles { get; set; }

    public virtual DbSet<TServicio> TServicios { get; set; }

    public virtual DbSet<TTurno> TTurnos { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<TDetalle>(entity =>
        {
            entity.ToTable("T_Detalles");

            entity.HasIndex(e => e.ServicioId, "IX_T_Detalles_servicio_id");

            entity.HasIndex(e => e.TurnoId, "IX_T_Detalles_turno_id");

            entity.Property(e => e.Observaciones).IsRequired();
            entity.Property(e => e.ServicioId).HasColumnName("servicio_id");
            entity.Property(e => e.TurnoId).HasColumnName("turno_id");

            entity.HasOne(d => d.Servicio).WithMany(p => p.TDetalles).HasForeignKey(d => d.ServicioId);

            entity.HasOne(d => d.Turno).WithMany(p => p.TDetalles).HasForeignKey(d => d.TurnoId);
        });

        modelBuilder.Entity<TServicio>(entity =>
        {
            entity.ToTable("T_Servicios");

            entity.Property(e => e.EnPromocion).HasColumnName("enPromocion");
            entity.Property(e => e.Nombre).IsRequired();
        });

        modelBuilder.Entity<TTurno>(entity =>
        {
            entity.ToTable("T_Turnos");

            entity.Property(e => e.Cliente).IsRequired();
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}